//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionGroupBuilder.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectionGroupBuilder.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionGroup Builder [BETA].
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong or empty properties..
        /// </summary>
        public static string BadPropertiesError {
            get {
                return ResourceManager.GetString("BadPropertiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name:.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string ExecuteScript {
            get {
                return ResourceManager.GetString("ExecuteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script has been executed..
        /// </summary>
        public static string ExecutionComplete {
            get {
                return ResourceManager.GetString("ExecutionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New GUID.
        /// </summary>
        public static string GenerateGuid {
            get {
                return ResourceManager.GetString("GenerateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate XML File.
        /// </summary>
        public static string GenerateXml {
            get {
                return ResourceManager.GetString("GenerateXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages:.
        /// </summary>
        public static string PackagesList {
            get {
                return ResourceManager.GetString("PackagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Path to File.
        /// </summary>
        public static string PathToFile {
            get {
                return ResourceManager.GetString("PathToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add App-V File.
        /// </summary>
        public static string PickFile {
            get {
                return ResourceManager.GetString("PickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script:.
        /// </summary>
        public static string PowerShellScript {
            get {
                return ResourceManager.GetString("PowerShellScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script.
        /// </summary>
        public static string PowerShellScriptWindow {
            get {
                return ResourceManager.GetString("PowerShellScriptWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, script is executing..
        /// </summary>
        public static string ProgressBarExecuting {
            get {
                return ResourceManager.GetString("ProgressBarExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: &quot;set-executionpolicy remotesigned&quot; allows to execute unsigned scripts..
        /// </summary>
        public static string PSNote {
            get {
                return ResourceManager.GetString("PSNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Execution works only if there is unsigned scripts execution allowed in PowerShell..
        /// </summary>
        public static string PSNote0 {
            get {
                return ResourceManager.GetString("PSNote0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveScript {
            get {
                return ResourceManager.GetString("SaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is too less packages on the list..
        /// </summary>
        public static string ToLessPackagesError {
            get {
                return ResourceManager.GetString("ToLessPackagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
